configuration:
  - changed-files:
      - any-glob-to-any-file:
          - '.circleci/**/*'
          - '.contentful/**/*'
          - '.github/**/*'
          - '.dependabot/**/*'
          - '.eslintrc.cjs'
          - 'eslint.config.mjs'
          - '.gitignore'
          - '.nvmrc'
          - '.prettierrc'
          - 'lerna.json'
          - 'LICENSE'
          - 'nx.json'
          - 'tsconfig.base.json'
          - 'tsconfig.json'
