version: 2.1
orbs:
  vault: contentful/vault@1

executors:
  docker-with-node:
    docker:
      - image: cimg/node:18.17
    working_directory: ~/build-and-test

jobs:
  prepare:
    executor: docker-with-node
    steps:
      - checkout
      - run: node --version

  release-next:
    executor: docker-with-node
    steps:
      - checkout
      - use-vault
      - install-dependencies
      - vault/configure-lerna
      - run: echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > ~/.npmrc
      - run: yarn build # This should not be needed, but without it it will not contain any files
      # Use the exact dependency version for local path specifiers. e.g. this avoids resolving `^0.0.2-alpha.15` to `0.0.2-dev-20240114T223125.0`
      - run: yarn lerna version --exact --no-private --conventional-commits --conventional-prerelease --preid next --create-release github --yes
      - run: yarn lerna publish from-git --pre-dist-tag next --yes

workflows:
  version: 2
  build_and_test:
    jobs:
      - prepare
