/**
 * ⚠️ WARNING: DO NOT MODIFY THIS FILE DIRECTLY ⚠️
 *
 * This file is auto-generated by reexportFromSdk.js before each build.
 * Any direct modifications will be overwritten.
 *
 * To make changes, modify the source barrel file and run the build script.
 *
 * Note: any 'export * from' statements in the source barrel file will be ignored. Export items individually.
 */

export {
  defineComponents,
  maintainBasicComponentIdsWithoutPrefix,
  useFetchById,
  useFetchBySlug,
} from '@contentful/experiences-sdk-react';
export {
  VisualEditorMode,
  createExperience,
  defineBreakpoints,
  defineDesignTokens,
  detachExperienceStyles,
} from '@contentful/experiences-core';
export {
  CF_STYLE_ATTRIBUTES,
  CONTENTFUL_COMPONENTS,
  LATEST_SCHEMA_VERSION,
} from '@contentful/experiences-core/constants';
export type { ComponentDefinition } from '@contentful/experiences-core/types';
