name: Build and Test

on: push

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress install
        uses: cypress-io/github-action@v5
        with:
          runTests: false
          build: npm run build
      - name: Run Linting
        run: npm run lint
      - name: Save build folder
        uses: actions/upload-artifact@v3
        with:
          name: build-folders
          if-no-files-found: error
          path: |
            packages/components/dist
            packages/test-app/dist 
  component-tests:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download the build folders
        uses: actions/download-artifact@v3
        with:
          name: build-folders
      - name: Run CT Tests
        uses: cypress-io/github-action@v5
        with:
          command: npm run test
