export const CONTENTFUL_SECTION_ID = 'contentful-section'
export const CONTENTFUL_CONTAINER_ID = 'contentful-container'
export const CONTENTFUL_SECTION_NAME = 'Section'
export const CONTENTFUL_CONTAINER_NAME = 'Container'
export const CONTENTFUL_COMPONENT_CATEGORY = 'contentful-component'
