name: 'dependabot approve-and-request-merge'

on: pull_request_target

jobs:
  worker:
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    # github.event.pull_request.user.login checks the actual PR author
    # also verify the repository to prevent workflow runs on forks
    if: |
      github.event.pull_request.user.login == 'dependabot[bot]' &&
      github.repository == 'contentful/experience-builder'
    steps:
      - name: Fetch Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
      - name: Auto-merge
        # Don't auto-merge major version upgrades
        if: ${{steps.dependabot-metadata.outputs.update-type != 'version-update:semver-major'}}
        uses: contentful/github-auto-merge@v1
        with:
          VAULT_URL: ${{ secrets.VAULT_URL }}
