name: Build and Test

on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true

jobs:
  install-build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Echo ref_name'
        run: echo ${{ github.ref_name }}
      - name: 'Checkout'
        uses: actions/checkout@v4
      - name: 'Use NodeJS 20'
        uses: actions/setup-node@v4
        with:
          node-version: '20.11'
          cache: 'npm'
      - name: Restore Cypress Binary
        uses: actions/cache/restore@v4
        id: restore-cypress
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-${{ hashFiles('./package-lock.json') }}
          restore-keys: cypress-${{ runner.os }}-
      - name: Authenticate with private NPM package
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
      - name: Install dependencies
        run: npm ci
      - name: Save Cypress Binary
        if: steps.restore-cypress.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-${{ hashFiles('./package-lock.json') }}
      - name: Build app
        run: |
          npm run build
      - name: List components folder
        run: ls -la packages/components
      - name: Save Build folders        
        uses: actions/cache/save@v4
        with:
          path: |
            packages/*/dist
            packages/*/build
            packages/test-apps/react-vite/dist
            packages/test-apps/nextjs/.next
          key: build-cache-${{ github.run_id }}-${{ github.run_attempt }}
