name: 'Run Checks: Lint & Tests'

on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true
      PACT_BROKER_BASE_URL:
        required: true
      PACT_BROKER_TOKEN:
        required: true

env:
  GIT_BRANCH: ${{ github.ref_name }}
  GIT_COMMIT: ${{ github.sha }}
  ENABLE_PACTFLOW: ${{ vars.ENABLE_PACTFLOW }}

jobs:
  # this job relies on the install-build workflow to run first
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: 'Use NodeJS 20'
        uses: actions/setup-node@v4
        with:
          node-version: '20.11'
          cache: 'npm'
      - name: Restore Cypress Binary
        uses: actions/cache/restore@v4
        id: restore-cypress
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-${{ hashFiles('./package-lock.json') }}
          restore-keys: cypress-${{ runner.os }}-
      - name: Authenticate with private NPM package
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
      - name: Install dependencies
        run: npm ci
      - name: Restore the build folders
        uses: actions/cache/restore@v4
        with:
          path: |
            packages/*/dist
            packages/*/build
            packages/test-apps/react-vite/dist
            packages/test-apps/nextjs/.next
          key: build-cache-${{ github.run_id }}-${{ github.run_attempt }}
      - name: List components folder
        run: ls -la packages/components
      - name: List component build folders
        run: ls -la packages/components/dist
      - name: List test-app build folders
        run: ls -la packages/test-apps/react-vite/dist
      - name: Run Prettier
        run: npm run prettier:check
      - name: Run Linting
        run: npm run lint
      - name: Run Dependency Cruiser
        run: npm run depcruise
      - name: Run TSC
        run: npm run tsc
      - name: Run Unit Tests
        run: npm run test:coverage
        env:
          PACT_BROKER_BASE_URL: ${{ secrets.PACT_BROKER_BASE_URL }}
          PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}
      - name: Run CT Tests
        run: npm run test:component
      - name: Publish pacts between Experiences SDK and User Interface
        if: env.ENABLE_PACTFLOW == 'true'
        run: >-
          docker run --rm -v ${PWD}:${PWD}
          -e PACT_BROKER_BASE_URL
          -e PACT_BROKER_TOKEN
          pactfoundation/pact-cli publish ${PWD}/pacts
          --consumer-app-version ${GIT_COMMIT} --branch ${GIT_BRANCH}
        env:
          PACT_BROKER_BASE_URL: ${{ secrets.PACT_BROKER_BASE_URL }}
          PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}
          GIT_COMMIT: ${{ env.GIT_COMMIT }}
          GIT_BRANCH: ${{ env.GIT_BRANCH }}
      - name: Save test results to artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-assets
          if-no-files-found: error
          path: |
            packages/*/reports
            packages/*/reports/clover.xml
            pacts
