name: Main

on:
  push:
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      publish-prerelease:
        description: 'Publish prerelease version of the selected branch'
        required: false
        default: false
        type: boolean

jobs:
  install-build:
    uses: ./.github/workflows/build.yaml
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  check:
    needs: install-build
    uses: ./.github/workflows/check.yaml
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  vercel:
    needs: [install-build, check]
    uses: ./.github/workflows/vercel.yaml
    secrets:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  publish:
    needs: [install-build, check]
    if: >-
      (github.ref_name == 'main' ||
        github.ref_name == 'development' ||
        github.ref_name == 'next' ||
        inputs.publish-prerelease 
      ) &&
      !contains(github.event.head_commit.message, 'skip-release') &&
      github.actor != 'dependabot[bot]' &&
      github.actor != 'contentful-automation[bot]'
    permissions:
      contents: write
      id-token: write
    uses: ./.github/workflows/publish.yaml
    with:
      publish-prelease: ${{ !!inputs.publish-prerelease }}
    secrets:
      VAULT_URL: ${{ secrets.VAULT_URL }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  upload-artifact-cleanup:
    if: ${{ always() }}
    needs: [install-build, check, publish]
    permissions:
      actions: write
    uses: ./.github/workflows/cleanup.yaml
