name: Deploy demo apps to Vercel

on:
  workflow_call:
    inputs:
      publish-web-apps-to-prod:
        description: "Publish web apps to prod"
        default: false
        required: false
        type: boolean
    secrets:
      VERCEL_TOKEN:
        required: true
      VERCEL_ORG_ID:
        required: true
      VAULT_URL:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Retrieve Secrets from Vault
        id: vault
        uses: hashicorp/vault-action@v3.4.0
        with:
          url: ${{ secrets.VAULT_URL }}
          role: ${{ github.event.repository.name }}-github-action
          method: jwt
          path: github-actions
          exportEnv: false
          secrets: |
            secret/data/github/github_packages_read GITHUB_PACKAGES_READ_TOKEN | GITHUB_PACKAGES_READ_TOKEN ;
      - name: "Checkout"
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Checkout all branches and tags, needed for publish
          ref: ${{ github.event.workflow_run.head_branch || github.ref }}
          token: ${{ steps.vault.outputs.GITHUB_PACKAGES_READ_TOKEN }}

      - name: "Use NodeJS 20"
        uses: actions/setup-node@v4
        with:
          node-version: "20.11"
          cache: "npm"

      - name: Setup npmrc
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ steps.vault.outputs.GITHUB_PACKAGES_READ_TOKEN }}" > .npmrc
          echo "@contentful:registry=https://npm.pkg.github.com" >> .npmrc
      - name: Install dependencies
        run: npm ci
      - name: Restore the build folders
        uses: actions/cache/restore@v4
        with:
          path: |
            packages/*/dist
            packages/*/build
            packages/test-apps/react-vite/dist
            packages/test-apps/nextjs/.next
            packages/templates/nextjs-marketing-demo/.next
            packages/templates/react-vite-ts/dist
          key: build-cache-${{ github.run_id }}-${{ github.run_attempt }}
      - name: Install Vercel CLI
        run: npm install --global vercel@canary
      - name: "Deploy vite test-app site to Vercel"
        env:
          # Domain: experience-builder-test-app.colorfuldemo.com
          VERCEL_PROJECT_ID: prj_wr3mJgz9qLeHh33UaCFquePsr1hw
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          REF_NAME: ${{ github.ref_name }}
          PUBLISH_TO_PROD: ${{ inputs.publish-web-apps-to-prod }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          GH_TOKEN: ${{ steps.vault.outputs.GITHUB_PACKAGES_READ_TOKEN }}
          NPM_TOKEN: ${{ steps.vault.outputs.GITHUB_PACKAGES_READ_TOKEN }}
        run: |
          if [ "$REF_NAME" = "main" ] || [ "$PUBLISH_TO_PROD" = "true" ]; then
            vercel pull --yes --environment=production --token="$VERCEL_TOKEN"
            vercel build --prod --token="$VERCEL_TOKEN"
            vercel deploy --prod --prebuilt --token="$VERCEL_TOKEN"
          else
            vercel pull --yes --environment=preview --token="$VERCEL_TOKEN"
            vercel build --token="$VERCEL_TOKEN"
            vercel deploy --prebuilt --token="$VERCEL_TOKEN"
          fi
      - name: "Deploy nextjs-marketing-demo site to Vercel"
        env:
          # Domain: studio-nextjs-marketing-demo.colorfuldemo.com
          VERCEL_PROJECT_ID: prj_CQ1K4Pbkx5SQq2Fi9c4ZPHloOv79
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          REF_NAME: ${{ github.ref_name }}
          PUBLISH_TO_PROD: ${{ inputs.publish-web-apps-to-prod }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          GH_TOKEN: ${{ steps.vault.outputs.GITHUB_PACKAGES_READ_TOKEN }}
          NPM_TOKEN: ${{ steps.vault.outputs.GITHUB_PACKAGES_READ_TOKEN }}
        run: |
          if [ "$REF_NAME" = "main" ] || [ "$PUBLISH_TO_PROD" = "true" ]; then
            vercel pull --yes --environment=production --token="$VERCEL_TOKEN"
            vercel build --prod --token="$VERCEL_TOKEN"
            vercel deploy --prod --prebuilt --token="$VERCEL_TOKEN"
          else
            vercel pull --yes --environment=preview --token="$VERCEL_TOKEN"
            vercel build --token="$VERCEL_TOKEN"
            vercel deploy --prebuilt --token="$VERCEL_TOKEN"
          fi
      - name: "Deploy react vite template site to Vercel"
        env:
          # Domain studio-react-vite-template.colorfuldemo.com
          VERCEL_PROJECT_ID: prj_HoAvIbgvZ3gYJDLCAaNsHIpBvI0k
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          REF_NAME: ${{ github.ref_name }}
          PUBLISH_TO_PROD: ${{ inputs.publish-web-apps-to-prod }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          GH_TOKEN: ${{ steps.vault.outputs.GITHUB_PACKAGES_READ_TOKEN }}
          NPM_TOKEN: ${{ steps.vault.outputs.GITHUB_PACKAGES_READ_TOKEN }}
        run: |
          if [ "$REF_NAME" = "main" ] || [ "$PUBLISH_TO_PROD" = "true" ]; then
            vercel pull --yes --environment=production --token="$VERCEL_TOKEN"
            vercel build --prod --token="$VERCEL_TOKEN"
            vercel deploy --prod --prebuilt --token="$VERCEL_TOKEN"
          else
            vercel pull --yes --environment=preview --token="$VERCEL_TOKEN"
            vercel build --token="$VERCEL_TOKEN"
            vercel deploy --prebuilt --token="$VERCEL_TOKEN"
          fi
